routes/user.go

supports https://github.com/bitclout/frontend/pull/67

add option to skip hodlings when getting users stateless

---

routes/transaction.go

check that username doesn't belong to user updating profile before raising username already exists error

FIX: Case sensitive username updates

---

routes/exchange.go
routes/post.go

Related PRs: 
https://github.com/bitclout/core/pull/25
https://github.com/bitclout/frontend/pull/96

Add hasMedia flag to determine if only posts with media are returned

---

cmd/config.go
cmd/node.go
cmd/run.go
routes/exchange.go
routes/exchange_test.go
routes/global_state.go
routes/server.go
routes/shared.go
routes/user.go

add super admin public keys flag and separate out super admin routes. move admin public keys flag to this repo

Super Admin Public Keys

---

go.sum
routes/server.go
routes/shared.go
routes/user.go

add get single profile picture endpoint, remove profile pic from profile entry response to lighten payloads

Get single profile picture endpoint

---

routes/user.go

Meant to be deployed in concert with: https://github.com/bitclout/frontend/pull/156

Add txn outputs to basic transfer notifications.

---

routes/base.go
routes/server.go

keep one hours worth of last trade price history and take the max of those values

Track last hour of pricing data

---

Dockerfile
cmd/node.go
cmd/run.go
config/config.go
go.mod
go.sum
routes/base.go
routes/exchange_test.go
routes/global_state.go
routes/media.go
routes/server.go
routes/shared.go
routes/transaction.go
routes/user.go
routes/verify.go
routes/wyre.go

I also cleaned up the large number of params we were passing to APIServer.

Add email verification flow

---

routes/transaction.go
routes/user.go

Add a switch for CLOUT diamonds vs creator coin diamonds

CLOUT Diamonds

---

routes/admin_node.go
routes/exchange.go
routes/server.go
routes/transaction.go
scripts/tools/toolslib/chain.go

Remove bitcoin sync from backend

WIP Feat/remove bitcoin sync

---

routes/wyre.go

replace source amount and amount includes fee with amount to allow apple pay

fix: Wyre apple pay

---

routes/admin_nft.go
routes/nft.go
routes/post.go
routes/transaction.go
routes/user.go

- move getVerifiedUsernameToPKIDMap calls outside of loops and helper functions
- remove unnecessary call to get the profile entry response in augmentProfileEntry

Performance enhancements

---

routes/nft.go

fixes `mismatched types *bool and bool`

Fix mismatched types

---

README.md

I added some common errors I encountered in setting up locally, and their solutions, to the README, and encouraged other devs to do the same

Add helpful debugging tips to the README

---

go.mod
go.sum
routes/server.go
scripts/tools/toolslib/jwt.go

Same library, now maintained by community. Old library has CVE.

Update JWT lib

---

routes/transaction.go

Include the txn hash hex of the basic transfer transaction used to comp profile creation

Return Txn Hash Hex of Profile Creation Compensation in UpdateProfile

---

routes/user.go

Reverts deso-protocol/backend#225 until core PR is merged.

Revert "add support for nft transfer notifications"

---

routes/user.go

reopening PR until core PR is merged.

add support for nft transfer notifications

---

routes/base.go

This PR adds the default Fees to Get App State - which seems sensible as it returns already Create Profile fees as well as Node Tx Fees.

add default tx fees to app state

---

routes/admin_referrals.go
routes/nft.go
routes/post.go
routes/server.go

Add endpoint to fetch NFTs created by user
blocked by https://github.com/deso-protocol/core/pull/161

get nfts created by user

---

cmd/run.go
config/config.go
routes/server.go
routes/supply.go
routes/transaction.go

Note: This is functionality that is required to get DESO verified on CoinMarketCap

add supply monitoring to backend to support TotalSupply and Rich List  functionality

---

routes/verify.go

https://github.com/Jumio/implementation-guides/blob/master/netverify/callback.md#reject-reason

rejectReasonDetails from Jumio can be either and array or single object, so treat it as an interface

---

routes/admin_jumio.go
routes/global_state.go
routes/server.go
routes/verify.go

Also fix bug related to getting the referral amount for the referrer. Needed to check AllowCustomKickbackAmount instead of AllowCustomReferralAmount

add endpoint to manage default kickback amount

---

routes/server.go
routes/supply.go

- add endpoint to fetch this value

Update supply monitoring to get count of keys with non-zero balance

---

routes/user.go

remove blacklisted public keys from notifications

---

go.sum
routes/exchange.go
routes/hot_feed.go
routes/message.go
routes/nft.go
routes/post.go
routes/tutorial.go
routes/user.go
scripts/nodes/n0
scripts/nodes/n0_test

Make backend work for core DAO changes

---

routes/message.go
routes/post.go

TODO: Need to fully test messages locally before deploying this change

Fix compile errors for messages v3

---

routes/admin_buy_deso.go
routes/admin_jumio.go
routes/base.go
routes/eth.go
routes/post.go
routes/server.go
routes/transaction.go
routes/verify.go
routes/wyre.go

Also more efficiently check if poster is only graylisted (not blacklisted) in get single post

Cache reserve exchange rate, buy deso fee basis points, and jumio default values from global state

---

routes/media.go
routes/message.go
routes/nft.go
routes/shared.go
routes/transaction.go
routes/user.go

Add ExtraData to relevant responses

add ExtraData to the request to construct CreateNFT, PrivateMessage, GroupMessagingKey, and AuthorizeDerivedKey transactions

---

routes/dao_coin_exchange.go
routes/server.go
routes/transaction.go

Manual testing looks good on local node:
```
{
"Orders": [
{
"BuyingDAOCoinCreatorPublicKeyBase58Check": "",
"ExchangeRateCoinsToSellPerCoinToBuy": 0.19230769230769232,
"OperationType": "ASK",
"OrderID": "74cdb017057fc2b3ea26cbe2cd284f85e571d766d3b712154db28929ef1a133f",
"QuantityToFill": 3.1,
"SellingDAOCoinCreatorPublicKeyBase58Check": "tBCKVERmG9nZpHTk2AVPqknWc1Mw9HHAnqrTpW1RnXpXMQ4PsQgnmV",
"TransactorPublicKeyBase58Check": "tBCKVz4QBMWnk1PybMwKNYxjKaVAi6r4Byj5EZuYTdhyP2RiuSRbWS"
},
{
"BuyingDAOCoinCreatorPublicKeyBase58Check": "tBCKVERmG9nZpHTk2AVPqknWc1Mw9HHAnqrTpW1RnXpXMQ4PsQgnmV",
"ExchangeRateCoinsToSellPerCoinToBuy": 1.1,
"OperationType": "BID",
"OrderID": "8a75ed075f19d8106e218292d2f2c72b5a0e96e30919101b80f8eab0b2e4339d",
"QuantityToFill": 1.2, …
```

Create new endpoint to get open DAO coin limit orders by transactor

---

routes/base.go
routes/server.go

add raw exchange prices to response

---

routes/user.go

Relevant code in core: https://github.com/deso-protocol/core/blob/main/lib/mempool.go#L1789-L1881.

Create notifications when associations are created.

---

routes/access_group.go
routes/access_group_test.go
routes/server.go

More commits to be merged on top of https://github.com/deso-protocol/backend/pull/430 @lazynina

Fixing tests and adding new APIs on top of Ln/access group api modifications

---

routes/access_group.go
routes/new_message.go
routes/server.go

add update access group, remove access group members, update access group members, update dm message, and update group chat message endpoints

Additional Access Group Endpoints

---

routes/hot_feed.go
routes/server.go
routes/supply.go
scripts/nodes/n0
scripts/tools/clear_ancestral_records.go
test.Dockerfile

Update hypersync to use default badger settings, switch to performance settings once hypersync completes

Update badger sync settings to optimize memory usage during hypersync

---

cmd/run.go
config/config.go
routes/admin_jumio.go
routes/base.go
routes/exchange.go
routes/exchange_test.go
routes/global_state.go
routes/hot_feed.go
routes/server.go
routes/supply.go
routes/transaction.go
routes/verify.go
scripts/nodes/n0
scripts/nodes/n0_test
scripts/tools/clear_ancestral_records.go
test.Dockerfile

[stable] Release 3.4.4
add node version endpoint (#505)
Co-authored-by: Lazy Nina <>
[stable] Release 3.4.5
hotfix to exchange test
Add captcha verification (#509)
* Updates to captcha verification
* Updates to backend
* Updates to captcha verify
* Update captcha verification
* Cleanup logs
* Add routes to store reward amount in global state, track usage via data dog
* Update verify captcha validation ordering, add back comp profile config bool
Update badger sync settings to optimize memory usage during hypersync (#506)
* Update hypersync to use default badger settings, switch to performance settings once hypersync completes
* Update test dockerfile to accept core branch name as parameter
* Blank commit to trigger build
ln/fix-transaction-info-mempool (#510)
Co-authored-by: Lazy Nina <> …

merge main into feature pos

---

scripts/global_params/update_global_params.go

Add Script To Make Global Params Changes on Regtest Node
Remove public key

Add Script To Make Global Params Changes on Regtest Node

---

.github/workflows/ci.yaml
Dockerfile
go.mod
test.Dockerfile

This reverts commit 53adfeed13af6121f11d8758914c0d7899654a90.

Revert "Upgrade go to 1.22 (#585)"

---

routes/hot_feed.go

There was an issue preventing posts older than 4h from being considered for the hot feed, caused by the shift from 5m per block to 1.5s per block (it was originally 60d then it became 4h).

Fix hot feed

---

routes/atomic_txns.go

Allows you to use raw hexes to construct the txn, enabling Python sdk at Openfund v2 launch.
Fully tested here:
* https://github.com/deso-protocol/amm-service/pull/16

Simplify atomic txn construction
