deso-protocol/backend

routes/user.go

Off by one error in getPublicKeyToProfileEntryMapForFollows. This issue is caused by an erroneous clause when checking if number of fetched followers is satisfied.

Fixed error in numToFetch break for follower fetch

---

routes/user.go

This adds support for fallback images in the "get profile picture" endpoint.  Meant to be deployed before the frontend PR here: https://github.com/bitclout/frontend/pull/150

Add support for fallback picture in get profile picture endpoint.

---

cmd/config.go
cmd/node.go
cmd/run.go
routes/server.go
routes/transaction.go
routes/wyre.go

While working on updates to the documentation, I realized that this flag's name was confusing if a node only supports `Buy with BTC`

rename WyreBTCAddress to BuyBitCloutBTCAddress to more accurately reflect this flag's purpose

---

routes/message.go
routes/shared.go

Backend receives EncryptedMessageText (hex) encrypted using shared secret from the frontend. V2 to distinguish between new and legacy encryption schemes.

Add shared secret encryption/decryption

---

scripts/nodes/n0
scripts/nodes/n0_test
scripts/nodes/n1
scripts/nodes/n1_test
scripts/nodes/n2
scripts/nodes/n2_test

Currently when I ran these node scripts on my MacOSX system it wasn't able to resolve the shebang `/bin/env`.
```
zsh: ./n0_test: bad interpreter: /bin/env: no such file or directory
```
Reading more I found out that `/usr/bin/env` is more compatible with most `*nix` based systems. This PR is to change it.
For reference - https://www.cyberciti.biz/tips/finding-bash-perl-python-portably-using-env.html
OS | env path
-- | --
OpenBSD | /usr/bin/env
FreeBSD | /usr/bin/env
Debian | /usr/bin/env
Ubuntu | /usr/bin/env
CentOS | /usr/bin/env
macOS | /usr/bin/env
SUSE | /usr/bin/env
RHEL | /usr/bin/env
NetBSD | /usr/bin/env
Solaris | /usr/bin/env

shebang compatible with *nix systems

---

routes/server.go
routes/user.go

Fixes #75 
New endpoint to check if one public key is holding the creator coin of another public key, returns true/flag flag and the BalanceEntry if coin is being held.

Add IsHodlingPublicKey endpoint

---

cmd/node.go
routes/server.go

Noticed some segfaults when sending SIGTERM to backend. It appears that the `quit` channel is never created and the `APIServer` pointer on the node data structure was not being set.

Fix graceful shutdown of backend node

---

routes/admin_transaction.go
routes/server.go
routes/transaction.go

Several places in `backend` hardcoded the public key base 58 prefix `BC` and `tBC`. This PR updates the code to compute this prefix dynamically based on `Params`, which can be useful if the prefix has been adjusted (for example, in a private testnet.)

Remove hardcoded base58 key prefixes and compute based on params

---

routes/nft.go

This is useful for identifying the sender of a transferred NFT.

Includes last owner public key in NFTEntryResponse if NFT is pending

---

routes/server.go

When running a global state node we do not send the AdminPublicKey param and we were not making it to the "*" check. This PR moves that check to the very start of the method.

Fix wildcard behavior for admin public keys

---

routes/server.go

In order to support profile creation compensation + submitting the transaction to this node, we need to expose this route.

add submit-transaction endpoint to list of public routes

---

routes/eth.go

Why make this change?
There was an instance where the ETH tx mined, so we broke out of the loop that polls Infura's API, but then in FinishETHTx, the call to get the tx from Infura's API returned a tx without a block number, so we aborted.
This change will prevent this discrepancy.

validate the transaction passed in instead of fetching from API again

---

routes/exchange.go

This endpoint has supported pagination for a while now. For performance, we need to phase out un-paginated responses.

Set default limit for TransactionInfo to 1000

---

routes/transaction.go

Without this change, we will completely abandon a txn in the event that
we detect a double-spend. Instead, what we should do is wait to see if
the txn eventually gets mined. If it does, then we should pay the user.
The code added by this commit is very ugly, error-prone, and hard to
test. In order to test it, I added temporary code to make the
double-spend check fail with high probability. This triggered the retry
logic, and I verified that the DESO was sent exactly once.

Add retries for txns when we detect a double-spend

---

Dockerfile
routes/admin_jumio.go
routes/base.go
routes/global_state.go
routes/global_state_test.go
routes/server.go
routes/verify.go
test.Dockerfile
utils/iso-3166-1-alpha-3-codes.go

**Why?**
This change will allow us to adjust the amount users from each country receive when verifying with Jumio. Currently, the approach has been to turn off jumio for countries that have users who are trying to game the verification system. After this change, we'll be able to open up to more countries and modify the amount we give as a sign-up bonus.
**What's been done:**
- create utils directory and a constant that allows us to look up country names from country alpha-3 codes
- Add admin endpoints to get all sign-up bonus configurations and edit a single country's sign up bonus amount
- Default sign-up bonus amount is now specified in USD cents instead of DeSo nanos
- Update Jumio callback to use the new logic to get amount to pay referrer and referee
- Fix global state tests.

Give different sign-up bonus amounts based on country of ID

---

routes/supply.go

When running n0_test, taking the slice up to 1000 would result in a panic since the length of the rich list would be less than 1000

use min of richListLength constant and length of rich list when taking the top 1k

---

routes/post.go

If offset is greater than top level comment count, don't add comments
This will prevent the same comments from being loaded twice if the number of comments in the post is less than the offset

Fix top-level comment offset issue

---

routes/nft.go

Depends on https://github.com/deso-protocol/core/pull/224

Include the AcceptedBlockHeight in the BidEntryResponse if it exists

---

routes/exchange.go
routes/extra_data_utils.go

Values in the ExtraData field can be encoded in different ways. The decoding needs to match the encoding used for each field.
Before:
```
"ExtraData": {
"DiamondLevel": "\u0002",
"DiamondPostHash": "~\ufffd+v\u2c45\u0010p\ufffdt\u000e%\ufffd\ufffd\fd\ufffd(\ufffd&\ufffd\ufffd\ufffdsO\u0019\u04fa\u0282$"
},
```
After:
```
"ExtraData": {
"DiamondLevel": "1",
"DiamondPostHash": "7eba2b76e2b1851070f2740e25c1c70c64a228e226f0dff5734f19d3baca8224"
},
```

Enable proper decoding for extra data values

---

routes/transaction.go

The endpoint only checks for transactions in the mempool. It needs to check the db as well to find older transactions.

return transactions from db in api/v0/get-txn/ endpoint

---

routes/transaction.go

This is blocked until we merge the DAO coin limit order feature branch in core.

Add DAOCoinLimitOrderLimitMap to TransactionSpendingLimitResponse

---

routes/extra_data_utils.go
routes/media.go

The current hex.Decode inadvertently requires all input values to be valid hex encoded strings. We want to allow any string value, not just hex encoded ones.

Use string <-> []byte casting as default for encoding extra data

---

routes/dao_coin_exchange.go
routes/dao_coin_exchange_test.go
routes/transaction.go

The API converts exchange rates and quantities back and forth from the float64 values provided by clients to the uint256 values used in core. This PR adds proper handing for back and forth conversions between the two.
Exchange rate field:
- If an order is buying a DAO coin and selling $DESO, we scale down the exchange rate by (1e38 * 1e-9) to account for the fact that 1 $DESO is equal to 1e9 nanos whereas 1 DAO coin is equal to 1e18 base units
- If an order is buying $DESO and selling a DAO coin, then we scale the exchange rate by (1e38 * 1e9) for the same reason
- If an order is buying and selling $DAO coins, we scale by 1e38 only
The quantity field:
- If the quantity field refers to $DESO, then we use 1e9 for scaling float coin quantities to uint256 $DESO nanos
- If the quantity field …

Conversion of DAO coin limit order exchange rates and quantities from float64 <-> uint256

---

routes/nft.go

Currently core may return some nil BidEntries when getting the accepted bid history. This should no longer happen after https://github.com/deso-protocol/core/pull/357 goes in, but this check will help prevent future issues as well.

Fix GetAcceptedBidHistory

---

cmd/run.go
scripts/tools/clear_ancestral_records.go
scripts/tools/compare_database.go
scripts/tools/compare_prefix.go
scripts/tools/compute_db_checksum.go
scripts/tools/copy_node_db.go

If you were to start a node and then immediately stop it, the backend node would have continued to run indefinitely. This PR fixes this.

Fix node shutdown

---

routes/dao_coin_exchange.go
routes/transaction.go

This is already validated in core, but this check will provide more immediate feedback to the user if there is a relevant error message.

Validate DAO coin order transfer restriction.

---

routes/post.go
routes/server.go

Added an endpoint get-posts-hashlist which can retrieve posts from an array of PostHashes.
Sample payload:
```
{
"PostsHashList": ["bdebcb4b5ebf10bd20f8db3e8be55d5b618c7302ea7415967079c4ed58a746e6", "62ef62991f56d05f6cf55f06080d64e438a6529d58fae57822f1ab9cf34600f1","ba448a92b26a3aa4a2fb5e3f8d03e1956f87f26192503c6dd13031c34d9ea54a", "3a4d6f5b50512f36ed868c406e522775bba9637502cb9708ff3fbb451c70baf5" ],
"ReaderPublicKeyBase58Check": "BC1YLhDaBCuTnctb44A9yV4hiQu2GV3g3672nHyDYxQoSQ3E7Jk2QHY",
"OrderBy": ""
}
```
I have multiple projects waiting for this:
- DeSocialWorld
- Gemstori
- Videso

Feature get posts hashlist

---

routes/user.go

In order to support parsing of spending limit hexes from before the unlimited transaction spending limit migration, we need to be able to pass an optional query param to specify the block height at which we want to parse this spending limit hex.

Backwards compatibility support for GetTransactionSpendingLimitResponseFromHex

---

routes/media.go
routes/server.go

Adds new endpoint /get-video-dimensions that only returns dimensions (and doesn't require any credentials).

Get video dimensions

---

routes/admin_user.go
routes/exchange.go
routes/expose_global_state.go
routes/global_state.go
routes/post.go
routes/server.go
routes/user.go

Currently, nodes are only able to blacklist by profile. This means that if an account is using a deceptive username that should be blocked, once blacklisted it can simply switch the name to a new profile and continue on. This change creates a list of blocked usernames that will always be blocked, rather than tracking the profiles themselves.

Blacklist and graylist by username

---

Dockerfile
routes/miner.go

* The Dockerfile change in this PR switches us to compiling with debug
settings. This slows things down a bit but it's worth it because it
means we can attach debugging instances directly to a running node
remotely.
* Otherwise, this is just extra logging.

Fix minor issues to speed up block processing logic

---

Dockerfile

I'm updating our run repo and the Entrypoint in our Dockerfile for backend currently waits until you connect a deubgger to it to keep going. This fixes it.

Make dlv --continue rather than waiting for a debugger in Dockerfile

---

routes/server.go
routes/user.go

There wasn't a clean way to get the balance of a set of coins, which is needed in order to determine if the amm should initialize a market. Added this endpoint to address this need.
There's also a thorough test for it in the amm code here:
https://github.com/deso-protocol/amm-service/blob/f4953a8f1a141110a10f2ced44e7983176d5d46e/ammlib/amm_config_test.go#L1170

Add simple balance endpoint (for amm usage)

---

config/config.go
routes/dao_coin_exchange_with_fees.go
routes/server.go
routes/shared.go
routes/transaction.go
routes/user.go

- Add AmmMetadataPublicKey as an optional backend flag. This flag is required to be set if you want to SET or GET trading fees for DaoCoinLimitOrderWithFee.
- Updated trading fees to be an association set by the AmmMetadataPublicKey rather than by the individual user. This allows users to credibly disable trading fee updates. Tests are in the amm-service repo and all are passing.
- Fixed a bunch of issues related to using DESO as the quote currency in a DaoCoinLimitOrderWithFees transaction. Thorough and updated tests are in the amm-service repo and all tests are passing there.
- Added a new backend endpoint to get all holders of a coin WITH locked balances as well. This was needed in order to support lockup-based features when creating a coin, without having to add a dependency on …

Updates to support smoother AMM coin creation in Focus

---

routes/dao_coin_exchange_with_fees.go
routes/transaction.go

- Reproduced the limit order issue reported by @lazynina locally
- Tested and verified that this code fully fixes it
- Searched for all the places we were using a non-coinbase price. Found one and left a comment but didn't change it
- Also fixed and merged in amm-service

Use coinbase price for DESO in dao-coin-limit-order
